[libdefaults]
    default_realm = __KRB5_REALM__
    udp_preference_limit = 1
    rdns = false
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true

[realms]
    __KRB5_REALM__ = {
        kdc = __KRB5_KDC__:88
        admin_server = __KRB5_KDC__:749
    }

[domain_realm]
    .__KRB5_DOMAIN__ = __KRB5_REALM__
    __KRB5_DOMAIN__ = __KRB5_REALM__
